name: jira-reporting-actions
on:
  push:
    paths: 
     - 'JiraReporting/*.json'
jobs:
  do-something-on-runner-job:
    runs-on: [self-hosted, windows, x64, LSBE927268-labels]
    name: step-for-in-runner-testing
    steps:
    - run: echo "hello there handsome!"
    - run: whoami
    - run: pwd
    - run: ls "../../../../*"
  changedfiles:
    runs-on: [self-hosted, windows, x64, LSBE927268-labels]
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
  lint:
    runs-on: [self-hosted, windows, x64, LSBE927268-labels]
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.ts}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.ts}}

