name: jira-reporting-actions
on: [push]
jobs:
  start-runner-job:
    runs-on: [self-hosted, ubuntu-latest]
    name: babycrawl
    steps:
    - name: test
    - run: echo "hello there handsome!"
      shell: bash
