name: jira-reporting-actions
on: [push]
jobs:
  do-something-on-runner-job:
    runs-on: [self-hosted, windows, x64, LSBE927268-labels]
    name: step-for-in-runner
    steps:
    - run: echo "hello there handsome!"
    - run: whoami
 
 