name: jira-reporting-actions
on:
  push:
    paths: 
     - 'JiraReporting/*.json'
jobs:
  do-something-on-runner-job:
    runs-on: [self-hosted, windows, x64, LSBE927268-labels]
    name: step-for-in-runner-testing
    steps:
    - run: echo "hello there handsome!"
    - run: whoami
    - run: pwd
    - run: ls "../../../../*"
  changedfiles-job:
    runs-on: [atc-ubuntu-latest]
    steps:
    # Map a step output to a job output
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files using separator
        id: changed-files-eol
        uses: tj-actions/changed-files@v24
        with:
          files: |
            '**/*.json'
          files_ignore: |
            '**/*.yml'
          separator: 
            "\n" |
          quotepath: |
            "true" |
      - name: List all changed files
        run: |
           echo ${{ steps.changed-files-eol.outputs.all_changed_files }}
           for file in ${{ steps.changed-files-eol.outputs.all_changed_files }}; do
             echo "$file was changed"
           done
#      - name: exotic for w tr
#        run: |
#          printf "${{ steps.changed-files-eol.outputs.all_changed_files }}"
#          echo "Files changed array"
#          printf "\n"
#          
#          ${{ steps.changed-files-eol.outputs.all_changed_files }}
#          for file in $(tr ',' '\n' <<< "${{ steps.changed-files-eol.outputs.all_changed_files }}"); do echo "$file"; done
#
#          for v in $(tr ',' '\n' <<< "$var") ; do something_with "$v" ; done
#    outputs:
#      all: ${{ steps.changes.outputs.all}}
#      ts: ${{ steps.changes.outputs.ts }}
#    steps:
#      - name: pre-run check
#        run: ls -lst
#        # Make sure we have some code to diff.
#      - name: Checkout repository
#        uses: actions/checkout@v2
#      - name: Get changed files
#        id: changes
#        # Set outputs using the command.
#        run: |
#          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
#          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
#      - name: post-run check
#        run: ls -lst
#  lint:
#    runs-on: [atc-ubuntu-latest]
#    # require the first job to have ran
#    needs: changedfiles
#    # only run there are changed files
#    if: ${{needs.changedfiles.outputs.ts}}
#    steps:
#      - name: echo changed files
#        run: echo ${{needs.changedfiles.outputs.ts}}



#      - name: Get changed files using defaults
#        id: changed-files
#        uses: tj-actions/changed-files@v24
#        with:
#          files: |
#            **/*.json
#          files_ignore: |
#            *.yml

