name: jira-reporting-actions
on:
  push:
    paths: 
     - '**/*.json'
env:
  JIRAUSER: ${{ secrets.JIRA_USER }}
  JIRAPASS: ${{ secrets.JIRA_PASS }}
jobs:
  changedfiles-job:
    runs-on: [atc-ubuntu-latest]
    steps:
    # Map a step output to a job output
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files using separator
        id: changed-files-eol
        uses: tj-actions/changed-files@v24
        with:
          files: |
            **/*.json
          files_ignore: |
            **/*.yml
      - name: Use changed files as payload to update Jira
        if: steps.changed-files-eol.outputs.any_changed == 'true'
        run: |
           echo "Update Jira with dependency tree in the changed file: "
           for file in ${{ steps.changed-files-eol.outputs.all_changed_files }}; do
             bash ./JiraReporting/jqUpdateJson.sh $file
           done

