name: jira-reporting-actions
on: [push]
jobs:
  start-runner-job:
    runs-on: [self-hosted, ubuntu-latest]
    name: babycrawl
  do-my-thing-job:
    name: boom
    steps:
    - name: test
      run: echo "hello there handsome!"
      shell: bash
