name: jira-reporting-actions
on:
  push:
    paths: 
     - 'JiraReporting/*.json'
jobs:
  do-something-on-runner-job:
    runs-on: [self-hosted, windows, x64, LSBE927268-labels]
    name: step-for-in-runner
    steps:
#    - run: echo "hello there handsome!"
#    - run: whoami
#    - run: pwd
#    - run: ls "../../../../*"
     - uses: jitterbit/get-changed-files@v1
     - run: |
         for changed_file in ${{ steps.files.outputs.all }}; do
           echo "Do something with this ${changed_file}."
         done